package io.mindspice.magenta2.ai.skills;

public enum AgentSkillDiagnosticCode {
    SKILL_PATH_INVALID,
    SKILL_PATH_ESCAPE_REJECTED,
    SKILL_SYMLINK_REJECTED,
    SKILL_MD_MISSING,
    SKILL_MD_READ_FAILED,
    SKILL_FRONTMATTER_MISSING,
    SKILL_FRONTMATTER_YAML_INVALID,
    SKILL_FRONTMATTER_YAML_FALLBACK_USED,
    SKILL_NAME_MISSING,
    SKILL_NAME_INVALID,
    SKILL_NAME_TOO_LONG,
    SKILL_NAME_DIRECTORY_MISMATCH,
    SKILL_DESCRIPTION_MISSING,
    SKILL_DESCRIPTION_TOO_LONG,
    SKILL_COMPATIBILITY_INVALID,
    SKILL_METADATA_INVALID,
    SKILL_ALLOWED_TOOLS_INVALID
}
