import { chromium } from 'playwright';
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
await page.goto('http://localhost:18080/skills');
await page.waitForTimeout(1000);
await page.locator('#skills-list').getByText('valid-skill').first().click();
await page.waitForTimeout(800);
const input=page.locator('input[name="agentId"]').first();
await input.click();
await input.pressSequentially('phase05', {delay:60});
await page.waitForTimeout(1200);
const options = page.locator('.entity-selector-option');
console.log('optCount', await options.count());
if (await options.count()) await options.first().click();
await page.waitForTimeout(400);
await page.getByRole('button',{name:'Assign'}).first().click();
await page.waitForTimeout(1200);
const panel = (await page.locator('#skills-assignment-panel').innerText()).replace(/\s+/g,' ');
console.log(panel.slice(0,600));
const unassign = page.getByRole('button',{name:/Unassign|Remove/i}).first();
console.log('unassignCount', await unassign.count());
if (await unassign.count()) { await unassign.click(); await page.waitForTimeout(900); console.log('after unassign', (await page.locator('#skills-assignment-panel').innerText()).replace(/\s+/g,' ').slice(0,300)); }
await page.screenshot({path:'artifacts/playwright/agent-skills-phase-05/desktop-focus3-after-assign.png',fullPage:true});
await browser.close();
