import { chromium } from 'playwright';
import fs from 'fs';
const agent = JSON.parse(fs.readFileSync('artifacts/playwright/agent-skills-phase-05/agent-create.json','utf8'));
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
await page.goto('http://localhost:18080/skills');
await page.waitForTimeout(1000);
await page.locator('#skills-list').getByText('valid-skill').first().click();
await page.waitForTimeout(700);
await page.locator('#skills-detail button',{hasText:'references'}).first().click();
await page.waitForTimeout(600);
await page.locator('input[name="fileName"]').fill('ref-phase05.txt');
await page.locator('.skill-add-file-form textarea[name="content"]').fill('ref content');
await page.getByRole('button',{name:'Add File'}).first().click();
await page.waitForTimeout(900);
const hasRef = await page.locator('#skills-detail').getByText('ref-phase05.txt').count();
console.log('hasRef',hasRef);

const input=page.locator('input[name="agentId"]').first();
await input.fill(agent.id);
await input.press('Tab');
await page.waitForTimeout(700);
await page.getByRole('button',{name:'Assign'}).first().click();
await page.waitForTimeout(1200);
const txt=await page.locator('#skills-assignment-panel').innerText();
console.log('panel',txt.replace(/\s+/g,' ').slice(0,350));
const unassign = await page.getByRole('button',{name:/Unassign|Remove/i}).count();
console.log('unassignCount',unassign);
await page.screenshot({path:'artifacts/playwright/agent-skills-phase-05/desktop-focus-after-assign.png',fullPage:true});
await browser.close();
